function initializeGUI(hObject,handles)



%% Clear variables in handles.DB
%Delete axes before remove DB field (reset from a menu), must delete axes from DB
%Delete lines on hmask
child_handles = allchild(handles.hmask);
delete(child_handles);

child_handles = allchild(handles.axespanel);

%Clear vertical guide (reset from a menu)
temp = findobj(child_handles,'Type','axes','-not', 'Tag','hmask');
delete(temp);

if ispc %Set the fontSize for windows & mac
    fntsize = 10;
else
    fntsize = 12;
end



strctfieldnames = fieldnames(handles);
z = strfind(strctfieldnames,'DB');
handles = rmfield(handles,strctfieldnames(cellfun(@(z)~isempty(z),strfind(strctfieldnames,'DB'))));

%% Pre-define color codes [r g b] : For signal plotting
handles.DB.flagcolor = 0; %initialize flag
handles.DB.colorcode{1} = [0 0 1];          %blue
handles.DB.colorcode{2} = [0 0.5 0];        %dark green
handles.DB.colorcode{3} = [1 0 0];          %red
handles.DB.colorcode{4} = [0 0.75 0.75];    %teal
handles.DB.colorcode{5} = [0.75 0 0.75];    %purple
handles.DB.colorcode{6} = [0.75 0.75 0];    %yellow-green
handles.DB.colorcode{7} = [0.25 0.25 0.25]; %grey
handles.DB.colorcode = handles.DB.colorcode(:); %column cell


%% Figure
guiname = 'McDAPS v.2.0';
set(handles.figMain,'Name',guiname);

%Specify component dimensions [pixel]
figw = 1280; %width of figure
figh = 720;  %height of figure
pnaw = 850;  %width of axes panel
pnah = 670;  %height of axes panel
pnww = 175;  %width of workspace panel
pnwh = 275;  %height of workspace panel
pnpw = 175;  %width of plot editor panel
pnph = 190;  %height of plot editor panel
pntw = 235;  %width of tag editor panel
pnth = 220;  %height of tag editor panel
pnew = 235;  %width of event markers panel
pneh = 315;  %height of event markers panel
bsw = 24; %width of small rec buttons
bsh = 19; %height of small rec buttons

%Store dimensions in handles structure
handles.DB.figw = figw; 
handles.DB.figh = figh;
handles.DB.panelw = 850;
handles.DB.panelh = 670;

%Specify plot dimensions [pixel]
handles.DB.gaph = 25;    %gap between 2 subplots
handles.DB.splotx = 45;  %location of the lowest subplot
handles.DB.splotw = 795; %width of each subplot

%% Pointer
set(gcf,'pointer','arrow');

%% Toolbar
set(handles.toolLoadData,'Enable','on');
set(handles.toolZoomin,'Enable','off','State','off');
set(handles.toolZoomout,'Enable','off','State','off');
set(handles.toolPan,'Enable','off','State','off');
set(handles.toolDataCursor,'Enable','off','State','off');
set(handles.toolVerticalGuide_push,'Enable','off');
set(handles.toolEditPlot,'Enable','off','State','off');
set(handles.toolSelectRegion,'Enable','off');

%% Status bar
set(handles.editStatus1,...
    'Unit','normalized',...
    'Position',[1/figw,1/figh,639/figw,19/figh],... %1/figw = 1% because the unit is normalized to 1
    'String','',...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');


%% Viewing window & slider
set(handles.txtWindow,...
    'Unit','normalized',...
    'Position',[5/figw,27/figh,106/figw,18/figh],...
    'FontSize',fntsize,...
    'SelectionHighlight','off');
set(handles.popWindow,...
    'Unit','normalized',...
    'Position',[107/figw,25/figh,72/figw,23/figh],...
    'FontSize',fntsize,...
    'Value',1,...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.xslider,...
    'Unit','normalized',...
    'Position',[230/figw,25/figh,795/figw,20/figh],...
    'Min',0,'Max',1,'Value',0,...
    'Enable','off',...
    'SelectionHighlight','off');

%% Axes panel
set(handles.axespanel,...
    'Unit','normalized',...
    'Position',[185/figw,50/figh,pnaw/figw,pnah/figh],...
    'SelectionHighlight','off');

%% HMASK
%set(handles.hmask,'Visible','off','XTick',[],'YTick',[],'Unit','normalized','Position',[handles.DB.splotx/handles.DB.panelw 0 handles.DB.splotw/handles.DB.panelw 1],'Parent',handles.axespanel);
set(handles.hmask,'Unit','normalized','Position',[handles.DB.splotx/handles.DB.panelw 0 handles.DB.splotw/handles.DB.panelw 1],'FontUnits','normalized','Visible','off');
set(handles.hmask,'Color','none','YTick',[],'XTick',[],'XColor','none','YColor','none','XLim',[0 1],'YLim',[0 1]);
axes(handles.hmask);

hguide = displayVerticalGuide2(handles.figMain,handles.hmask,handles.editStatus1,'r');
handles.DB.vertguide.hl = hguide;
set(hguide,'Visible','off');

%% Listboxes for loaded variables

% ********** Current folder **********
set(handles.txtMatfiles,...
    'Unit','normalized',...
    'Position',[5/figw,700/figh,100/figw,15/figh],...
    'FontSize',fntsize,...
    'SelectionHighlight','off');

set(handles.listMatfiles,...
    'Unit','normalized',...
    'Position',[5/figw,645/figh,175/figw,55/figh],...
    'String','',...
    'FontSize',fntsize,...
    'Value',1,...
    'BackgroundColor',[1,1,1],...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Variables **********
set(handles.txtMatvars,...
    'Unit','normalized',...
    'Position',[5/figw,621/figh,60/figw,15/figh],...
    'FontSize',fntsize,...
    'SelectionHighlight','off');

set(handles.butAllmatvars,...
    'Unit','normalized',...
    'Position',[70/figw,616/figh,110/figw,24/figh],...
    'FontSize',fntsize,...
    'TooltipString','Add all variables to Workspace without plotting',...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.chkPlotmatvars,...
    'Unit','normalized',...
    'Position',[5/figw,600/figh,170/figw,19/figh],...
    'FontSize',fntsize,...
    'Value',0,...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.listMatvars,...
    'Unit','normalized',...
    'Position',[5/figw,525/figh,175/figw,75/figh],...
    'String','',...
    'FontSize',fntsize,...
    'Min',0,'Max',2',...    %Allow user to select >1 items
    'Value',1,...
    'BackgroundColor',[1,1,1],...
    'Enable','off',...
    'SelectionHighlight','off');

%% Workspace

% ********** Panel **********
set(handles.panelWrkspc,...
    'Unit','normalized',...
    'Position',[5/figw,245/figh,pnww/figw,pnwh/figh],...
        'FontSize',fntsize,...
    'SelectionHighlight','off');

% ********** Workspace listbox **********
set(handles.listWrkspc,...
    'Unit','normalized',...
    'Position',[2/pnww,182/pnwh,171/pnww,92/pnwh],...
    'Min',0,'Max',2,...
    'String','',...
    'FontSize',fntsize,...
    'Value',1,...
    'BackgroundColor',[1,1,1],...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** File name **********
set(handles.txtFilename,...
    'Unit','normalized',...
    'Position',[2/pnww,161/pnwh,26/pnww,18/pnwh],...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.editFilename,...
    'Unit','normalized',...
    'Position',[30/pnww,160/pnwh,142/pnww,19/pnwh],...
    'String','',...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Variable size **********
set(handles.txtVarsize,...
    'Unit','normalized',...
    'Position',[2/pnww,140/pnwh,60/pnww,18/pnwh],...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.editVarsize,...
    'Unit','normalized',...
    'Position',[63/pnww,139/pnwh,109/pnww,19/pnwh],...
    'String','',...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Normalize **********
set(handles.chkNorm,...
    'Unit','normalized',...
    'Position',[2/pnww,117/pnwh,173/pnww,19/pnwh],...
    'String','Normalize (mu=0, std=1)',...
    'FontSize',fntsize,...
    'Value',0,...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Detrend **********
set(handles.chkDetrend,...
    'Unit','normalized',...
    'Position',[2/pnww,97/pnwh,173/pnww,19/pnwh],...
    'String','Detrend Order:',...
    'FontSize',fntsize,...
    'Value',0,...
    'Enable','off',...ย
    'SelectionHighlight','off');

set(handles.editDetrend,...
    'Unit','normalized',...
    'Position',[111/pnww,97/pnwh,40/pnww,19/pnwh],...
    'String','',...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Scale **********
set(handles.chkScale,...
    'Unit','normalized',...
    'Position',[2/pnww,76/pnwh,110/pnww,19/pnwh],...
    'FontSize',fntsize,...
    'Value',0,...
    'Enable','off',...
    'SelectionHighlight','off');
 
set(handles.editScale,...
    'Unit','normalized',...
    'Position',[111/pnww,76/pnwh,40/pnww,19/pnwh],...
    'String','',...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');




% ********** Sampling frequency **********
set(handles.chkFs,...
    'Unit','normalized',...
    'Position',[2/pnww,52/pnwh,70/pnww,19/pnwh],...
    'FontSize',fntsize,...
    'Value',0,...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.editFs,...
    'Unit','normalized',...
    'Position',[111/pnww,52/pnwh,40/pnww,19/pnwh],...
    'String','',...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

%% Plot editor

% ********** Panel **********
set(handles.panelPloteditor,...
    'Unit','normalized',...
    'Position',[5/figw,50/figh,pnpw/figw,pnph/figh],...
    'Title',[],...
    'SelectionHighlight','off');

% ********** Plot order **********
set(handles.txtPlotorder,...
    'Unit','normalized',...
    'Position',[2/pnpw,175/pnph,80/pnpw,15/pnph],...
    'FontSize',fntsize,...
    'SelectionHighlight','off');

set(handles.listPlotorder,...
    'Unit','normalized',...
    'Position',[2/pnpw,115/pnph,145/pnpw,60/pnph],...
    'String','',...
    'FontSize',fntsize,...
    'Min',0,'Max',2',...
    'Value',1,...
    'BackgroundColor',[1,1,1],...
    'Enable','off',...
    'SelectionHighlight','off');
                              
set(handles.butDeleteplot,...
    'Unit','normalized',...
    'Position',[149/pnpw,156/pnph,24/pnpw,19/pnph],...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');
                              
set(handles.butUpplot,...
    'Unit','normalized',...
    'Position',[149/pnpw,136/pnph,24/pnpw,19/pnph],...
    'FontSize',fntsize,...
    'ForegroundColor',0.5*ones(1,3),...
    'Enable','off',...
    'SelectionHighlight','off');
                          
set(handles.butDownplot,...
    'Unit','normalized',...
    'Position',[149/pnpw,116/pnph,24/pnpw,19/pnph],...
    'FontSize',fntsize,...
    'ForegroundColor',0.5*ones(1,3),...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Plotted variables **********
set(handles.txtPlotvars,...
    'Unit','normalized',...
    'Position',[2/pnpw,95/pnph,120/pnpw,15/pnph],...
    'FontSize',fntsize,...
    'SelectionHighlight','off');
                            
set(handles.listPlotvars,...
    'Unit','normalized',...
    'Position',[2/pnpw,35/pnph,145/pnpw,60/pnph],...
    'String','',...
    'FontSize',fntsize,...
    'Min',0,'Max',2',...
    'Value',1,...
    'BackgroundColor',[1,1,1],...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.butDeleteplotvar,...
    'Unit','normalized',...
    'Position',[149/pnpw,76/pnph,24/pnpw,19/pnph],...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

% ********** Color & line styles **********
set(handles.butColor,...
    'Unit','normalized',...
    'Position',[2/pnpw,9/pnph,55/pnpw,24/pnph],...
    'FontSize',fntsize,...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.txtColor,...
    'Unit','normalized',...
    'Position',[2/pnpw,6/pnph,55/pnpw,5/pnph],...
    'BackgroundColor',[0,0,0],...
    'SelectionHighlight','off');

set(handles.popLinestyle,...
    'Unit','normalized',...
    'Position',[60/pnpw,6/pnph,113/pnpw,25/pnph],...
    'FontSize',fntsize,...
    'Value',1,...
    'Enable','off',...
    'SelectionHighlight','off');
%% StudyNote
% set(handles.editStudyNote,...
%     'Unit','normalized',...
%     'Position',[1040/figw,370/figh,pntw/figw,pnth/figh],...
%     'FontSize',10,...
%     'SelectionHighlight','off');

%% Tag editor
handles.editorTags = {};
handles.tagsavepath = [];
set(handles.panelTageditor,...
    'Unit','normalized',...
    'Position',[1040/figw,0.53,pntw/figw,pnth/figh],... %50% in the figure's height
    'FontSize',fntsize,...
    'SelectionHighlight','off');
set(handles.tableEditor,'Data',{},...
    'Enable','on',...
    'Unit','normalized',...
    'Position',[2/pntw,25/pnth,231/pntw,0.80]);
set(handles.butSavetags,'Enable','off',...
    'Unit','normalized',...
    'Position',[1/pntw,6/pnth,bsw/pntw,bsh/pnth]);
set(handles.butTagManager,'Enable','on',...
    'Unit','normalized',...
    'FontSize',fntsize,...
    'Position',[26/pntw,6/pnth,bsw/pntw,bsh/pnth]);
set(handles.butDeletetag,'Enable','on',...
    'Unit','normalized',...
    'FontSize',fntsize,...
    'Position',[51/pntw,6/pnth,bsw/pntw,bsh/pnth]);
set(handles.chkSelectAll,'Enable','off',...
    'Unit','normalized',...
    'FontSize',fntsize,...
    'Position',[76/pntw,6/pntw,2*bsw/pntw,bsh/pnth]);


%% Tag Manager

handlesTM = guidata(handles.TagManager); 
handlesTM.importpath = [];
set(handlesTM.tableEditor,'Data',{});
set(handlesTM.tableViewer,'Data',{});
% Clear checkboxes
set(handlesTM.chkSelectAllEditor,'Value',0);
set(handlesTM.chkSelectAllViewer,'Value',0);

handlesTM.editorTags = {};
handlesTM.viewerTags = {}; %overwrite existing tags

guidata(handles.TagManager,handlesTM);


%% Event markers
set(handles.panelEvents,...
    'Unit','normalized',...
    'Position',[1040/figw,50/figh,pnew/figw,pneh/figh],...
    'FontSize',fntsize,...
    'SelectionHighlight','off');

set(handles.tableEvents,...
    'Unit','normalized',...
    'Position',[2/pnew,25/pneh,231/pnew,285/pneh],...
    'Data',{},...
    'Enable','off',...
    'SelectionHighlight','off');

set(handles.butInsertEvent,...
    'Unit','normalized',...
    'Position',[0.01,0.01,bsw/pnew,bsh/pneh],...
    'Enable','on');
set(handles.butSaveEvents,...
    'Unit','normalized',...
    'Position',[0.11,0.01,bsw/pnew,bsh/pneh],...
    'Enable','on');
set(handles.butOpenEvents,...
    'Unit','normalized',...
    'Position',[0.22,0.01,bsw/pnew,bsh/pneh],...
    'Enable','on');

set(handles.butJMP,'FontSize',fntsize);

%% 2016-06-29 Jump Editor and Button
set(handles.editFromToJMP,'String','');

%% Study note
set(handles.editStudyNote,'String',[],'HorizontalAlignment','left','Enable','inactive',...
    'Unit','normalized',...
    'FontSize',fntsize,...
    'Position',[1040/figw,0.84,0.18,0.15]);
%% Menubar: Layout
delete(get(handles.menuLayout,'Children'));
handles.menuDefineTemplate = uimenu('Parent',handles.menuLayout,'Label','Define Template','Enable','off');
handles.menuPlotTemplate   = uimenu('Parent',handles.menuLayout,'Label','Plot Template','Enable','off');

guidata(hObject, handles); %update handles structure

